import json
import os

cells = [
    # Header
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Data Analytics Project Work: Gas Turbine Emission & Energy Analysis\n",
            "**Course:** Data Analytics (and Data Driven Decision) — University of L'Aquila  \n",
            "**Dataset:** Gas Turbine CO and NOx Emission Data Set (2011–2015)  \n",
            "\n",
            "---\n",
            "## Project Guidelines Structure\n",
            "1. **Description of the dataset**\n",
            "2. **Data cleaning (if needed)**\n",
            "3. **Exploratory analysis**\n",
            "4. **Main analysis: objective and methods adopted**\n",
            "5. **Preview / summary of the results**\n",
            "6. **Detailed results**\n",
            "7. **Conclusions**\n",
            "\n",
            "---"
        ]
    },
    # Section 0
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 0. Setup and Environment\n",
            "Importing standard libraries required for data manipulation, analysis, and visualization."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import os\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "\n",
            "# Configure plot styling\n",
            "plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')\n",
            "plt.rcParams['figure.figsize'] = (12, 6)\n",
            "plt.rcParams['font.size'] = 11\n",
            "plt.rcParams['axes.titlesize'] = 13\n",
            "plt.rcParams['axes.labelsize'] = 11\n",
            "\n",
            "print(\"Environment initialized successfully.\")"
        ]
    },
    # Section 1
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 1. Description of the Dataset\n",
            "\n",
            "### 1.1 Context & Industrial Background\n",
            "The dataset comprises **36,733 hourly aggregated records** of 11 sensor measurements collected from an operational gas turbine located in the north-western region of Turkey across five consecutive years (**2011 to 2015**).\n",
            "\n",
            "The primary objective is the analysis, modeling, and prediction of flue gas emissions:\n",
            "- **Carbon Monoxide (CO)**: Key tracer of incomplete fuel combustion.\n",
            "- **Nitrogen Oxides (NOx = NO + NO2)**: Harmful pollutants formed at high peak flame temperatures (thermal NOx mechanism).\n",
            "- **Turbine Energy Yield (TEY)**: Net electrical power output produced by the turbine generator.\n",
            "\n",
            "### 1.2 Variable Definitions & Engineering Roles\n",
            "\n",
            "| Variable | Symbol | Unit | Category | Physical Role / Interpretation |\n",
            "| :--- | :--- | :--- | :--- | :--- |\n",
            "| Ambient Temperature | `AT` | °C | Ambient | Ambient intake air temperature; directly influences air density and mass flow rate. |\n",
            "| Ambient Pressure | `AP` | mbar | Ambient | Atmospheric barometric pressure surrounding the power plant. |\n",
            "| Ambient Humidity | `AH` | % | Ambient | Intake air relative humidity; influences flame temperature and moisture content. |\n",
            "| Air Filter Diff. Pressure | `AFDP` | mbar | Turbine | Pressure drop across the intake air filter (indicator of filter clogging). |\n",
            "| Gas Turbine Exhaust Pressure | `GTEP` | mbar | Turbine | Static exhaust backpressure in the expansion duct. |\n",
            "| Turbine Inlet Temperature | `TIT` | °C | Turbine | Firing temperature of hot combustion gas entering the expander. |\n",
            "| Turbine After Temperature | `TAT` | °C | Turbine | Exhaust gas temperature downstream of the expander. |\n",
            "| Compressor Discharge Pressure | `CDP` | mbar | Turbine | Pressure of compressed air exiting compressor stage. |\n",
            "| Turbine Energy Yield | `TEY` | MWh | Output | Hourly net electrical energy output generated by the unit. |\n",
            "| Carbon Monoxide | `CO` | mg/m³ | Emission | Measured flue gas CO concentration (incomplete combustion). |\n",
            "| Nitrogen Oxides | `NOX` | mg/m³ | Emission | Measured flue gas NOx concentration (thermal oxidation). |\n",
            "\n",
            "### 1.3 Data Ingestion & Concatenation"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "data_dir = os.path.join(\"data\", \"gas+turbine+co+and+nox+emission+data+set\")\n",
            "years = [2011, 2012, 2013, 2014, 2015]\n",
            "\n",
            "dfs = []\n",
            "for y in years:\n",
            "    fpath = os.path.join(data_dir, f\"gt_{y}.csv\")\n",
            "    df_y = pd.read_csv(fpath)\n",
            "    df_y['year'] = y\n",
            "    dfs.append(df_y)\n",
            "    print(f\"Year {y}: {df_y.shape[0]:,d} observations\")\n",
            "\n",
            "df_raw = pd.concat(dfs, ignore_index=True)\n",
            "print(f\"\\nTotal Combined Records: {df_raw.shape[0]:,d} rows × {df_raw.shape[1]} columns\")\n",
            "df_raw.head()"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 1.4 Initial Dataset Verification & Summary Statistics"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "sensor_cols = ['AT', 'AP', 'AH', 'AFDP', 'GTEP', 'TIT', 'TAT', 'TEY', 'CDP', 'CO', 'NOX']\n",
            "\n",
            "# Summary statistics\n",
            "stats_table = df_raw[sensor_cols].describe().T[['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']]\n",
            "stats_table.columns = ['Count', 'Mean', 'Std Dev', 'Min', 'Q1 (25%)', 'Median (50%)', 'Q3 (75%)', 'Max']\n",
            "stats_table.round(2)"
        ]
    },
    # Section 2
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 2. Data Cleaning, Quality Validation & Preprocessing\n",
            "\n",
            "Following the methodology taught in **Lecture 4 & Exercise 4.2**, we perform structured data quality validation:\n",
            "1. **Missing values verification** (`isnull().sum()`)\n",
            "2. **Duplicate detection and removal**\n",
            "3. **Physical range and sanity validation**\n",
            "4. **Outlier detection via $\\sigma$-clipping technique** with robust dispersion estimation:  \n",
            "   $$\\hat{\\sigma} = \\frac{\\text{IQR}}{1.35} = \\frac{Q_3 - Q_1}{1.35}$$\n",
            "   using the median as the location center to prevent outlier distortion.\n",
            "5. **Chronological dataset partitioning** into Training (2011–2013) and Testing (2014–2015) sets.\n",
            "6. **Standardization (Z-score normalization)**:  \n",
            "   $$z = \\frac{x - \\mu_{\\text{train}}}{\\sigma_{\\text{train}}}$$"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 2.1 Missing Values and Duplicates Check"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 1. Missing Values\n",
            "null_counts = df_raw[sensor_cols].isnull().sum()\n",
            "print(\"=== Missing Values per Feature ===\")\n",
            "print(null_counts)\n",
            "assert null_counts.sum() == 0, \"Unexpected null values detected!\"\n",
            "\n",
            "# 2. Duplicate Rows\n",
            "dup_count = df_raw[sensor_cols].duplicated().sum()\n",
            "print(f\"\\nDuplicate rows detected: {dup_count}\")\n",
            "\n",
            "# Remove duplicates\n",
            "df_clean = df_raw.drop_duplicates(subset=sensor_cols).copy().reset_index(drop=True)\n",
            "print(f\"Cleaned dataset size: {df_clean.shape[0]:,d} observations (removed {dup_count} duplicates)\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 2.2 Outlier Analysis via $\\sigma$-Clipping (Course Method)\n",
            "The standard deviation $\\sigma$ is highly sensitive to extreme outliers. As taught in class, we use the rank-based interquartile range (IQR) to estimate $\\hat{\\sigma} = \\text{IQR} / 1.35$ and inspect the data within $[\\text{Median} - 5\\hat{\\sigma},\\; \\text{Median} + 5\\hat{\\sigma}]$."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "sigma_records = []\n",
            "for col in sensor_cols:\n",
            "    q1, med, q3 = np.percentile(df_clean[col], [25, 50, 75])\n",
            "    iqr = q3 - q1\n",
            "    sigma_hat = iqr / 1.35\n",
            "    lower_bound = med - 5 * sigma_hat\n",
            "    upper_bound = med + 5 * sigma_hat\n",
            "    \n",
            "    outliers = ((df_clean[col] < lower_bound) | (df_clean[col] > upper_bound)).sum()\n",
            "    \n",
            "    sigma_records.append({\n",
            "        'Variable': col,\n",
            "        'Median': round(med, 2),\n",
            "        'IQR': round(iqr, 2),\n",
            "        'Estimated sigma_hat': round(sigma_hat, 2),\n",
            "        'Lower 5-sigma Bound': round(lower_bound, 2),\n",
            "        'Upper 5-sigma Bound': round(upper_bound, 2),\n",
            "        'Outliers Count (5-sigma)': outliers,\n",
            "        'Outliers %': f\"{(outliers / len(df_clean))*100:.2f}%\"\n",
            "    })\n",
            "\n",
            "df_sigma_table = pd.DataFrame(sigma_records)\n",
            "df_sigma_table"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 2.3 Chronological Train / Test Partitioning\n",
            "In accordance with the benchmark evaluation protocol:\n",
            "- **Training / Cross-Validation Set:** 2011–2013 (first 3 years)\n",
            "- **Independent Test Set:** 2014–2015 (last 2 years)"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "train_df = df_clean[df_clean['year'].isin([2011, 2012, 2013])].copy().reset_index(drop=True)\n",
            "test_df = df_clean[df_clean['year'].isin([2014, 2015])].copy().reset_index(drop=True)\n",
            "\n",
            "print(f\"Training Set (2011–2013): {train_df.shape[0]:,d} observations ({train_df.shape[0]/len(df_clean)*100:.2f}%)\")\n",
            "print(f\"Test Set (2014–2015):     {test_df.shape[0]:,d} observations ({test_df.shape[0]/len(df_clean)*100:.2f}%)\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 2.4 Feature Standardization (Z-score Normalization)\n",
            "To prevent data leakage, mean and standard deviation are computed strictly on the training set and applied to both training and test partitions."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "scaler_mean = train_df[sensor_cols].mean()\n",
            "scaler_std = train_df[sensor_cols].std()\n",
            "\n",
            "train_scaled = (train_df[sensor_cols] - scaler_mean) / scaler_std\n",
            "test_scaled = (test_df[sensor_cols] - scaler_mean) / scaler_std\n",
            "\n",
            "print(\"Standardization completed successfully.\")\n",
            "train_scaled.describe().round(2).T[['mean', 'std', 'min', 'max']]"
        ]
    },
    # Section 3
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 3. Exploratory Analysis (EDA)\n",
            "\n",
            "### 3.1 Course Definition of Exploratory Data Analysis\n",
            "As defined in the course lectures (**Slides 3, 10–18, 58, 64, 70 of `DA.pdf`**):\n",
            "> *\"A distribution is a way of representing how a variable is distributed in a population. Statistic is about synthesis: we synthesize distributions by measuring **Size (Center)** and **Spread (Variability)**.\"*\n",
            ">\n",
            "> *\"Principal Component Analysis (PCA) is a dimensionality reduction technique used for **exploratory data analysis (unsupervised learning)** and feature extraction (support to supervised learning).\"*\n",
            "\n",
            "In this section, we conduct:\n",
            "1. **Univariate Synthesis**: Measuring Size ($L_2$ Mean $\\mu$, $L_1$ Median, $L_0$ Mode) and Spread (Variance $\\sigma^2$, IQR, Gini Coefficient $G$).\n",
            "2. **Bivariate Association & Correlation**: Pearson correlation coefficient $r_{XY}$, collinearity inspection, and thermodynamic relationship analysis.\n",
            "3. **Multivariate Exploratory PCA**: Covariance matrix eigen-decomposition, Proportion of Variance Explained (PVE), Scree plot, and Biplot 2D projection."
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 3.2 Size & Spread Synthesis (Course Formulations)\n",
            "Implementing the Gini Coefficient from **Exercise 1.1**:\n",
            "$$G = \\frac{\\sum_{i=1}^n \\sum_{j=1}^n |x_i - x_j|}{2n \\sum_{i=1}^n x_i}$$"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def compute_gini(arr):\n",
            "    arr = np.sort(arr)\n",
            "    n = len(arr)\n",
            "    index = np.arange(1, n + 1)\n",
            "    return (2 * np.sum(index * arr) - (n + 1) * np.sum(arr)) / (n * np.sum(arr))\n",
            "\n",
            "eda_records = []\n",
            "for col in sensor_cols:\n",
            "    vals = train_df[col].values\n",
            "    q1, med, q3 = np.percentile(vals, [25, 50, 75])\n",
            "    iqr = q3 - q1\n",
            "    mean_val = np.mean(vals)\n",
            "    std_val = np.std(vals)\n",
            "    gini_val = compute_gini(vals)\n",
            "    \n",
            "    eda_records.append({\n",
            "        'Variable': col,\n",
            "        'Mean (L2 Center)': round(mean_val, 2),\n",
            "        'Median (L1 Center)': round(med, 2),\n",
            "        'Std Dev (Spread sigma)': round(std_val, 2),\n",
            "        'IQR (Spread Q3-Q1)': round(iqr, 2),\n",
            "        'Gini Coefficient G': round(gini_val, 3)\n",
            "    })\n",
            "\n",
            "df_eda_table = pd.DataFrame(eda_records)\n",
            "df_eda_table"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 3.3 Pearson Correlation Matrix and Collinearity Structure\n",
            "As taught in **Slide 64 & Slide 114**, Pearson's correlation coefficient evaluates linear dependence:\n",
            "$$r_{XY} = \\frac{\\sum_{i=1}^n (x_i - \\bar{x})(y_i - \\bar{y})}{\\sqrt{\\sum_{i=1}^n (x_i - \\bar{x})^2} \\sqrt{\\sum_{i=1}^n (y_i - \\bar{y})^2}}$$"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "corr_matrix = train_df[sensor_cols].corr()\n",
            "\n",
            "plt.figure(figsize=(10, 8))\n",
            "sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='Blues', vmin=-1, vmax=1,\n",
            "            cbar_kws={'label': \"Pearson Correlation Coefficient (r)\"})\n",
            "plt.title('Feature Correlation Matrix (Training Set 2011–2013)', fontsize=13, fontweight='bold', pad=12)\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 3.4 Key Thermodynamic Relationships & Emissions Trade-offs"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "fig, axes = plt.subplots(1, 3, figsize=(16, 4.8))\n",
            "sample_df = train_df.sample(3000, random_state=42)\n",
            "\n",
            "# 1. Ambient Temperature vs Energy Yield\n",
            "sns.scatterplot(data=sample_df, x='AT', y='TEY', ax=axes[0], color='#296299', alpha=0.4, s=20)\n",
            "axes[0].set_title('AT vs TEY: Ambient Temperature Effect\\n(r = -0.58, Air Density Loss)', fontweight='bold')\n",
            "axes[0].set_xlabel('Ambient Temperature AT (°C)')\n",
            "axes[0].set_ylabel('Turbine Energy Yield TEY (MWh)')\n",
            "\n",
            "# 2. Compressor Discharge Pressure vs Energy Yield\n",
            "sns.scatterplot(data=sample_df, x='CDP', y='TEY', ax=axes[1], color='#27ae60', alpha=0.4, s=20)\n",
            "axes[1].set_title('CDP vs TEY: Operating Pressure Work\\n(r = +0.99, Collinear Drive)', fontweight='bold')\n",
            "axes[1].set_xlabel('Compressor Discharge Pressure CDP (mbar)')\n",
            "axes[1].set_ylabel('Turbine Energy Yield TEY (MWh)')\n",
            "\n",
            "# 3. CO vs NOx Tradeoff\n",
            "sns.scatterplot(data=sample_df, x='CO', y='NOX', ax=axes[2], color='#e67e22', alpha=0.4, s=20)\n",
            "axes[2].set_title('CO vs NOx: Combustion Mechanism\\n(r = -0.37, Thermal NOx vs Incomplete Oxidation)', fontweight='bold')\n",
            "axes[2].set_xlabel('Carbon Monoxide CO (mg/m³)')\n",
            "axes[2].set_ylabel('Nitrogen Oxides NOx (mg/m³)')\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 3.5 Multivariate Unsupervised EDA: Principal Component Analysis (PCA)\n",
            "Implementing PCA via Covariance Matrix Eigen-decomposition (**Slide 75 of `DA.pdf`**):\n",
            "$$C = \\frac{1}{m} X^T X \\implies C v_i = \\lambda_i v_i$$\n",
            "$$\\text{PVE}_i = \\frac{\\lambda_i}{\\sum_{j=1}^n \\lambda_j}$$"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Scaled training data\n",
            "X_std = train_scaled.values\n",
            "\n",
            "# Covariance matrix\n",
            "C = np.cov(X_std, rowvar=False)\n",
            "\n",
            "# Eigenvalues and Eigenvectors\n",
            "eigenvalues, eigenvectors = np.linalg.eigh(C)\n",
            "\n",
            "# Sort descending\n",
            "idx = np.argsort(eigenvalues)[::-1]\n",
            "eigenvalues = eigenvalues[idx]\n",
            "eigenvectors = eigenvectors[:, idx]\n",
            "\n",
            "pve = eigenvalues / np.sum(eigenvalues)\n",
            "cum_pve = np.cumsum(pve)\n",
            "\n",
            "pca_summary = pd.DataFrame({\n",
            "    'Component': [f'PC{i:02d}' for i in range(1, 12)],\n",
            "    'Eigenvalue (Variance)': eigenvalues.round(3),\n",
            "    'Individual PVE (%)': (pve * 100).round(2),\n",
            "    'Cumulative PVE (%)': (cum_pve * 100).round(2)\n",
            "})\n",
            "pca_summary"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 3.6 PCA Scree Plot and Biplot Projection"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Scree Plot\n",
            "fig, ax1 = plt.subplots(figsize=(10, 5))\n",
            "ax1.bar(range(1, 12), pve * 100, color='#296299', alpha=0.85, label='Individual PVE (%)')\n",
            "ax1.set_xlabel('Principal Component Rank', fontweight='bold')\n",
            "ax1.set_ylabel('Proportion of Variance Explained (%)', color='#102542', fontweight='bold')\n",
            "ax1.set_xticks(range(1, 12))\n",
            "\n",
            "ax2 = ax1.twinx()\n",
            "ax2.plot(range(1, 12), cum_pve * 100, color='#d9534f', marker='o', linewidth=2.5, label='Cumulative PVE (%)')\n",
            "ax2.set_ylabel('Cumulative PVE (%)', color='#d9534f', fontweight='bold')\n",
            "ax2.grid(False)\n",
            "ax2.axhline(80, color='gray', linestyle='--', alpha=0.7, label='80% Cutoff')\n",
            "ax2.axhline(90, color='black', linestyle=':', alpha=0.7, label='90% Cutoff')\n",
            "\n",
            "plt.title('PCA Scree Plot & Cumulative Proportion of Variance Explained (PVE)', fontsize=13, fontweight='bold', pad=12)\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
            "\n",
            "# 2D Biplot\n",
            "scores_2d = X_std @ eigenvectors[:, :2]\n",
            "plt.figure(figsize=(9.5, 6.5))\n",
            "plt.scatter(scores_2d[:2500, 0], scores_2d[:2500, 1], alpha=0.25, color='#296299', s=15, label='Observations')\n",
            "\n",
            "scale_arrow = 3.8\n",
            "for i, var in enumerate(sensor_cols):\n",
            "    plt.arrow(0, 0, eigenvectors[i, 0]*scale_arrow, eigenvectors[i, 1]*scale_arrow,\n",
            "              head_width=0.12, head_length=0.12, fc='#c0392b', ec='#c0392b', linewidth=1.5)\n",
            "    plt.text(eigenvectors[i, 0]*scale_arrow*1.12, eigenvectors[i, 1]*scale_arrow*1.12, var,\n",
            "             color='#900C3F', fontweight='bold', fontsize=11, ha='center', va='center')\n",
            "\n",
            "plt.axhline(0, color='gray', linestyle='--', alpha=0.5)\n",
            "plt.axvline(0, color='gray', linestyle='--', alpha=0.5)\n",
            "plt.xlabel(f'PC1 ({pve[0]*100:.1f}% Variance Explained)', fontweight='bold')\n",
            "plt.ylabel(f'PC2 ({pve[1]*100:.1f}% Variance Explained)', fontweight='bold')\n",
            "plt.title('PCA Biplot: 2D Projection and Feature Loadings (Training 2011–2013)', fontsize=13, fontweight='bold', pad=12)\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    },
    # Section 4
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 4. Main Analysis: Objectives & Methods Adopted\n",
            "\n",
            "### 4.1 Objectives Formulation\n",
            "Based on the course curriculum and industrial objectives, the analysis is organized into three primary modeling goals:\n",
            "1. **Objective 1 — Turbine Energy Yield (TEY) Prediction & Multicollinearity Resolution**:\n",
            "   - Predict net electrical output from ambient and operating telemetry.\n",
            "   - Diagnose extreme multicollinearity via **Variance Inflation Factor (VIF, Slide 115)**.\n",
            "   - Overcome coefficient variance inflation using **Principal Component Regression (PCR, Slides 70, 106)**.\n",
            "2. **Objective 2 — Flue Gas Emissions Modeling (CO & NOx)**:\n",
            "   - Quantify pollutant concentration dynamics under changing operational and environmental conditions.\n",
            "   - Apply **Polynomial Regression (Slide 116 & Exercise 4.1)** to model non-linear low-load CO spikes ($x \\to [x, x^2]$) while preserving convex linear training.\n",
            "3. **Objective 3 — Operational Regime Discovery (Unsupervised Clustering)**:\n",
            "   - Partition the turbine operational space into distinct dispatch states via **K-Means Clustering (Slides 90–91)**.\n",
            "   - Validate cluster cohesion and separation using the **Silhouette Coefficient (Slide 94 & Exercise 3.1)**."
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 4.2 Multicollinearity Diagnostics via Variance Inflation Factor (VIF)\n",
            "As defined in **Slide 115 of `DA.pdf`**:\n",
            "$$\\text{VIF}(\\hat{\\beta}_j) = \\frac{1}{1 - R^2_{x_j | x_{-j}}}$$\n",
            "where $R^2_{x_j | x_{-j}}$ is the coefficient of determination obtained by regressing feature $x_j$ on all remaining predictors. A $\\text{VIF} > 10$ indicates severe multicollinearity."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "feature_cols = ['AT', 'AP', 'AH', 'AFDP', 'GTEP', 'TIT', 'TAT', 'CDP']\n",
            "X_tr_mat = train_df[feature_cols].values\n",
            "X_tr_std = (X_tr_mat - np.mean(X_tr_mat, axis=0)) / np.std(X_tr_mat, axis=0)\n",
            "\n",
            "vif_list = []\n",
            "for j, col in enumerate(feature_cols):\n",
            "    y_j = X_tr_std[:, j]\n",
            "    X_other = np.delete(X_tr_std, j, axis=1)\n",
            "    X_other_const = np.column_stack([np.ones(len(X_other)), X_other])\n",
            "    \n",
            "    beta_j = np.linalg.lstsq(X_other_const, y_j, rcond=None)[0]\n",
            "    pred_j = X_other_const @ beta_j\n",
            "    \n",
            "    rss_j = np.sum((y_j - pred_j)**2)\n",
            "    tss_j = np.sum((y_j - np.mean(y_j))**2)\n",
            "    r2_j = 1 - rss_j / tss_j\n",
            "    vif = 1 / (1 - r2_j)\n",
            "    \n",
            "    vif_list.append({\n",
            "        'Predictor Feature': col,\n",
            "        'R2 with Other Predictors': round(r2_j, 4),\n",
            "        'VIF Score': round(vif, 2),\n",
            "        'Collinearity Assessment': 'Severe Multicollinearity (VIF > 10)' if vif > 10 else 'Low / Acceptable'\n",
            "    })\n",
            "\n",
            "df_vif = pd.DataFrame(vif_list)\n",
            "df_vif"
        ]
    },
    # Section 5 & 6
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 5. Preview / Summary of the Results\n",
            "\n",
            "High-level comparison across all predictive models evaluated on the **Training Set (2011–2013)** and the independent **Out-of-Sample Test Set (2014–2015)**."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Load evaluation summary from run_detailed_analysis.py\n",
            "df_summary_res = pd.read_csv('figures/summary_results_table.csv') if os.path.exists('figures/summary_results_table.csv') else df_summary\n",
            "df_summary"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 6. Detailed Results & Diagnostics\n",
            "\n",
            "### 6.1 Model Coefficients, Standard Errors and 95% Confidence Intervals\n",
            "Following **Slide 111 of `DA.pdf`**, standard errors $\\sigma_{\\hat{\\beta}}$ and 95% confidence intervals $[\\hat{\\beta} - 2\\sigma_{\\hat{\\beta}},\\; \\hat{\\beta} + 2\\sigma_{\\hat{\\beta}}]$ are computed to evaluate statistical precision:"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Coefficients table for PCR (5 Principal Components for TEY)\n",
            "pcr_coefs = pd.DataFrame({\n",
            "    'Parameter': ['Intercept', 'PC1 Loading', 'PC2 Loading', 'PC3 Loading', 'PC4 Loading', 'PC5 Loading'],\n",
            "    'Estimated Beta': m_tey_pcr['beta'].round(4),\n",
            "    'Std Error (sigma_beta)': m_tey_pcr['se_beta'].round(4),\n",
            "    '95% CI Lower': m_tey_pcr['ci'][0].round(4),\n",
            "    '95% CI Upper': m_tey_pcr['ci'][1].round(4)\n",
            "})\n",
            "pcr_coefs"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 6.2 Actual vs. Predicted Visual Comparisons on Out-of-Sample Test Data (2014–2015)"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "fig, axes = plt.subplots(1, 3, figsize=(16, 5))\n",
            "\n",
            "# TEY PCR\n",
            "axes[0].scatter(m_tey_pcr['y_te'], m_tey_pcr['y_te_pred'], color='#296299', alpha=0.3, s=15)\n",
            "min_t, max_t = min(m_tey_pcr['y_te']), max(m_tey_pcr['y_te'])\n",
            "axes[0].plot([min_t, max_t], [min_t, max_t], 'r--', linewidth=2, label='Ideal 1:1 Line')\n",
            "axes[0].set_title(f\"TEY: PCR (5 Components)\\nTest R² = {m_tey_pcr['metrics_te'][0]:.4f} | RMSE = {m_tey_pcr['metrics_te'][1]:.2f} MWh\", fontweight='bold')\n",
            "axes[0].set_xlabel('Actual Energy Yield TEY (MWh)')\n",
            "axes[0].set_ylabel('Predicted Energy Yield TEY (MWh)')\n",
            "axes[0].legend()\n",
            "\n",
            "# CO Polynomial\n",
            "axes[1].scatter(m_co_poly['y_te'], m_co_poly['y_te_pred'], color='#e67e22', alpha=0.3, s=15)\n",
            "min_co, max_co = min(m_co_poly['y_te']), max(m_co_poly['y_te'])\n",
            "axes[1].plot([min_co, max_co], [min_co, max_co], 'r--', linewidth=2, label='Ideal 1:1 Line')\n",
            "axes[1].set_title(f\"CO: Polynomial (Degree 2)\\nTest R² = {m_co_poly['metrics_te'][0]:.4f} | RMSE = {m_co_poly['metrics_te'][1]:.2f} mg/m³\", fontweight='bold')\n",
            "axes[1].set_xlabel('Actual Carbon Monoxide CO (mg/m³)')\n",
            "axes[1].set_ylabel('Predicted Carbon Monoxide CO (mg/m³)')\n",
            "axes[1].legend()\n",
            "\n",
            "# NOX OLS\n",
            "axes[2].scatter(m_nox_ols['y_te'], m_nox_ols['y_te_pred'], color='#27ae60', alpha=0.3, s=15)\n",
            "min_nox, max_nox = min(m_nox_ols['y_te']), max(m_nox_ols['y_te'])\n",
            "axes[2].plot([min_nox, max_nox], [min_nox, max_nox], 'r--', linewidth=2, label='Ideal 1:1 Line')\n",
            "axes[2].set_title(f\"NOx: Full OLS\\nTrain R² = {m_nox_ols['metrics_tr'][0]:.4f} | Test RMSE = {m_nox_ols['metrics_te'][1]:.2f} mg/m³\", fontweight='bold')\n",
            "axes[2].set_xlabel('Actual Nitrogen Oxides NOx (mg/m³)')\n",
            "axes[2].set_ylabel('Predicted Nitrogen Oxides NOx (mg/m³)')\n",
            "axes[2].legend()\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 6.3 Diagnostic Residual Analysis (Slides 104, 108)"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "fig, axes = plt.subplots(2, 2, figsize=(14, 9))\n",
            "\n",
            "# TEY Residuals vs Predicted\n",
            "axes[0, 0].scatter(m_tey_pcr['y_te_pred'], m_tey_pcr['res_te'], color='#296299', alpha=0.3, s=15)\n",
            "axes[0, 0].axhline(0, color='r', linestyle='--', linewidth=1.5)\n",
            "axes[0, 0].set_title('TEY (PCR): Residuals vs Predicted', fontweight='bold')\n",
            "axes[0, 0].set_xlabel('Predicted TEY (MWh)')\n",
            "axes[0, 0].set_ylabel('Residual (Actual - Predicted)')\n",
            "\n",
            "# TEY Residual Distribution\n",
            "sns.histplot(m_tey_pcr['res_te'], kde=True, ax=axes[0, 1], color='#296299', bins=50)\n",
            "axes[0, 1].axvline(0, color='r', linestyle='--', linewidth=1.5)\n",
            "axes[0, 1].set_title('TEY (PCR): Residual Error Distribution (Zero-Centered)', fontweight='bold')\n",
            "axes[0, 1].set_xlabel('Residual Error (MWh)')\n",
            "\n",
            "# CO Residuals vs Predicted\n",
            "axes[1, 0].scatter(m_co_poly['y_te_pred'], m_co_poly['res_te'], color='#e67e22', alpha=0.3, s=15)\n",
            "axes[1, 0].axhline(0, color='r', linestyle='--', linewidth=1.5)\n",
            "axes[1, 0].set_title('CO (Poly): Residuals vs Predicted', fontweight='bold')\n",
            "axes[1, 0].set_xlabel('Predicted CO (mg/m³)')\n",
            "axes[1, 0].set_ylabel('Residual (Actual - Predicted)')\n",
            "\n",
            "# CO Residual Distribution\n",
            "sns.histplot(m_co_poly['res_te'], kde=True, ax=axes[1, 1], color='#e67e22', bins=50)\n",
            "axes[1, 1].axvline(0, color='r', linestyle='--', linewidth=1.5)\n",
            "axes[1, 1].set_title('CO (Poly): Residual Error Distribution', fontweight='bold')\n",
            "axes[1, 1].set_xlabel('Residual Error (mg/m³)')\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 6.4 Cross-Year Temporal Evaluation (2011 to 2015)"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "yearly_rows = []\n",
            "for m in models:\n",
            "    row = {'Model': m['name']}\n",
            "    for y in [2011, 2012, 2013, 2014, 2015]:\n",
            "        r2_val, rmse_val = m['yearly'][y]\n",
            "        row[f'{y} R2'] = round(r2_val, 3)\n",
            "    yearly_rows.append(row)\n",
            "df_yearly = pd.DataFrame(yearly_rows)\n",
            "df_yearly"
        ]
    }
]

notebook_content = {
    "cells": cells,
    "metadata": {
        "language_info": {
            "name": "python",
            "version": "3.11"
        },
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

with open("gas_turbine_analysis.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook_content, f, indent=2)

print("gas_turbine_analysis.ipynb updated with Section 5 and Section 6.")
