import json
import os

cells = [
    # Header
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Data Analytics Project Work: Gas Turbine Emission & Energy Analysis\n",
            "**Course:** Data Analytics (and Data Driven Decision) — University of L'Aquila  \n",
            "**Dataset:** Gas Turbine CO and NOx Emission Data Set (2011–2015)  \n",
            "\n",
            "---\n",
            "## Project Guidelines Structure\n",
            "1. **Description of the dataset**\n",
            "2. **Data cleaning (if needed)**\n",
            "3. **Exploratory analysis**\n",
            "4. **Main analysis: objective and methods adopted**\n",
            "5. **Preview / summary of the results**\n",
            "6. **Detailed results**\n",
            "7. **Conclusions**\n",
            "\n",
            "---"
        ]
    },
    # Section 0
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 0. Setup and Environment\n",
            "Importing core scientific libraries for data analysis and visualization."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import os\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "\n",
            "# Configure plot styling\n",
            "plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')\n",
            "plt.rcParams['figure.figsize'] = (12, 6)\n",
            "plt.rcParams['font.size'] = 11\n",
            "plt.rcParams['axes.titlesize'] = 13\n",
            "plt.rcParams['axes.labelsize'] = 11\n",
            "\n",
            "print(\"Environment initialized successfully.\")"
        ]
    },
    # Section 1
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 1. Description of the Dataset\n",
            "\n",
            "### 1.1 Context & Industrial Background\n",
            "The dataset comprises **36,733 hourly aggregated records** of 11 sensor measurements collected from an operational gas turbine located in the north-western region of Turkey across five consecutive years (**2011 to 2015**).\n",
            "\n",
            "The primary objective is the analysis, modeling, and prediction of flue gas emissions:\n",
            "- **Carbon Monoxide (CO)**: Key tracer of incomplete fuel combustion.\n",
            "- **Nitrogen Oxides (NOx = NO + NO2)**: Harmful pollutants formed at high peak flame temperatures (thermal NOx mechanism).\n",
            "- **Turbine Energy Yield (TEY)**: Net electrical power output produced by the turbine generator.\n",
            "\n",
            "### 1.2 Variable Definitions & Engineering Roles\n",
            "\n",
            "| Variable | Symbol | Unit | Category | Physical Role / Interpretation |\n",
            "| :--- | :--- | :--- | :--- | :--- |\n",
            "| Ambient Temperature | `AT` | °C | Ambient | Ambient intake air temperature; directly influences air density and mass flow rate. |\n",
            "| Ambient Pressure | `AP` | mbar | Ambient | Atmospheric barometric pressure surrounding the power plant. |\n",
            "| Ambient Humidity | `AH` | % | Ambient | Intake air relative humidity; influences flame temperature and moisture content. |\n",
            "| Air Filter Diff. Pressure | `AFDP` | mbar | Turbine | Pressure drop across the intake air filter (indicator of filter clogging). |\n",
            "| Gas Turbine Exhaust Pressure | `GTEP` | mbar | Turbine | Static exhaust backpressure in the expansion duct. |\n",
            "| Turbine Inlet Temperature | `TIT` | °C | Turbine | Firing temperature of hot combustion gas entering the expander. |\n",
            "| Turbine After Temperature | `TAT` | °C | Turbine | Exhaust gas temperature downstream of the expander. |\n",
            "| Compressor Discharge Pressure | `CDP` | mbar | Turbine | Pressure of compressed air exiting compressor stage. |\n",
            "| Turbine Energy Yield | `TEY` | MWh | Output | Hourly net electrical energy output generated by the unit. |\n",
            "| Carbon Monoxide | `CO` | mg/m³ | Emission | Measured flue gas CO concentration (incomplete combustion). |\n",
            "| Nitrogen Oxides | `NOX` | mg/m³ | Emission | Measured flue gas NOx concentration (thermal oxidation). |\n",
            "\n",
            "### 1.3 Data Ingestion & Concatenation"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "data_dir = os.path.join(\"data\", \"gas+turbine+co+and+nox+emission+data+set\")\n",
            "years = [2011, 2012, 2013, 2014, 2015]\n",
            "\n",
            "dfs = []\n",
            "for y in years:\n",
            "    fpath = os.path.join(data_dir, f\"gt_{y}.csv\")\n",
            "    df_y = pd.read_csv(fpath)\n",
            "    df_y['year'] = y\n",
            "    dfs.append(df_y)\n",
            "    print(f\"Year {y}: {df_y.shape[0]:,d} observations\")\n",
            "\n",
            "df_raw = pd.concat(dfs, ignore_index=True)\n",
            "print(f\"\\nTotal Combined Records: {df_raw.shape[0]:,d} rows × {df_raw.shape[1]} columns\")\n",
            "df_raw.head()"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 1.4 Initial Dataset Verification & Summary Statistics"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "sensor_cols = ['AT', 'AP', 'AH', 'AFDP', 'GTEP', 'TIT', 'TAT', 'TEY', 'CDP', 'CO', 'NOX']\n",
            "\n",
            "# Summary statistics\n",
            "stats_table = df_raw[sensor_cols].describe().T[['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']]\n",
            "stats_table.columns = ['Count', 'Mean', 'Std Dev', 'Min', 'Q1 (25%)', 'Median (50%)', 'Q3 (75%)', 'Max']\n",
            "stats_table.round(2)"
        ]
    },
    # Section 2
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 2. Data Cleaning, Quality Validation & Preprocessing\n",
            "\n",
            "Following the methodology taught in **Lecture 4 & Exercise 4.2**, we perform structured data quality validation:\n",
            "1. **Missing values verification** (`isnull().sum()`)\n",
            "2. **Duplicate detection and removal**\n",
            "3. **Physical range and sanity validation**\n",
            "4. **Outlier detection via $\\sigma$-clipping technique** with robust dispersion estimation:  \n",
            "   $$\\hat{\\sigma} = \\frac{\\text{IQR}}{1.35} = \\frac{Q_3 - Q_1}{1.35}$$\n",
            "   using the median as the location center to prevent outlier distortion.\n",
            "5. **Chronological dataset partitioning** into Training (2011–2013) and Testing (2014–2015) sets.\n",
            "6. **Standardization (Z-score normalization)**:  \n",
            "   $$z = \\frac{x - \\mu_{\\text{train}}}{\\sigma_{\\text{train}}}$$"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 2.1 Missing Values and Duplicates Check"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 1. Missing Values\n",
            "null_counts = df_raw[sensor_cols].isnull().sum()\n",
            "print(\"=== Missing Values per Feature ===\")\n",
            "print(null_counts)\n",
            "assert null_counts.sum() == 0, \"Unexpected null values detected!\"\n",
            "\n",
            "# 2. Duplicate Rows\n",
            "dup_count = df_raw[sensor_cols].duplicated().sum()\n",
            "print(f\"\\nDuplicate rows detected: {dup_count}\")\n",
            "\n",
            "# Remove duplicates\n",
            "df_clean = df_raw.drop_duplicates(subset=sensor_cols).copy().reset_index(drop=True)\n",
            "print(f\"Cleaned dataset size: {df_clean.shape[0]:,d} observations (removed {dup_count} duplicates)\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 2.2 Outlier Analysis via $\\sigma$-Clipping (Course Method)\n",
            "The standard deviation $\\sigma$ is highly sensitive to extreme outliers. As taught in class, we use the rank-based interquartile range (IQR) to estimate $\\hat{\\sigma} = \\text{IQR} / 1.35$ and inspect the data within $[\\text{Median} - 5\\hat{\\sigma},\\; \\text{Median} + 5\\hat{\\sigma}]$."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "sigma_records = []\n",
            "for col in sensor_cols:\n",
            "    q1, med, q3 = np.percentile(df_clean[col], [25, 50, 75])\n",
            "    iqr = q3 - q1\n",
            "    sigma_hat = iqr / 1.35\n",
            "    lower_bound = med - 5 * sigma_hat\n",
            "    upper_bound = med + 5 * sigma_hat\n",
            "    \n",
            "    outliers = ((df_clean[col] < lower_bound) | (df_clean[col] > upper_bound)).sum()\n",
            "    \n",
            "    sigma_records.append({\n",
            "        'Variable': col,\n",
            "        'Median': round(med, 2),\n",
            "        'IQR': round(iqr, 2),\n",
            "        'Estimated sigma_hat': round(sigma_hat, 2),\n",
            "        'Lower 5-sigma Bound': round(lower_bound, 2),\n",
            "        'Upper 5-sigma Bound': round(upper_bound, 2),\n",
            "        'Outliers Count (5-sigma)': outliers,\n",
            "        'Outliers %': f\"{(outliers / len(df_clean))*100:.2f}%\"\n",
            "    })\n",
            "\n",
            "df_sigma_table = pd.DataFrame(sigma_records)\n",
            "df_sigma_table"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 2.3 Visual Inspection of Sensor Distributions and Boxplots"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "fig, axes = plt.subplots(3, 4, figsize=(16, 11))\n",
            "axes = axes.flatten()\n",
            "\n",
            "for i, col in enumerate(sensor_cols):\n",
            "    sns.boxplot(y=df_clean[col], ax=axes[i], color='#3498db', width=0.4)\n",
            "    axes[i].set_title(f\"{col} Distribution\", fontweight='bold')\n",
            "    axes[i].set_ylabel(\"\")\n",
            "\n",
            "# Hide empty 12th subplot\n",
            "axes[-1].set_visible(False)\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 2.4 Chronological Train / Test Partitioning\n",
            "In accordance with the benchmark evaluation protocol:\n",
            "- **Training / Cross-Validation Set:** 2011–2013 (first 3 years)\n",
            "- **Independent Test Set:** 2014–2015 (last 2 years)"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "train_df = df_clean[df_clean['year'].isin([2011, 2012, 2013])].copy().reset_index(drop=True)\n",
            "test_df = df_clean[df_clean['year'].isin([2014, 2015])].copy().reset_index(drop=True)\n",
            "\n",
            "print(f\"Training Set (2011–2013): {train_df.shape[0]:,d} observations ({train_df.shape[0]/len(df_clean)*100:.2f}%)\")\n",
            "print(f\"Test Set (2014–2015):     {test_df.shape[0]:,d} observations ({test_df.shape[0]/len(df_clean)*100:.2f}%)\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 2.5 Feature Standardization (Z-score Normalization)\n",
            "To ensure equal weighting in multivariate analysis and prevent leakage, mean and standard deviation are computed strictly on the training set and then applied to transform both training and testing partitions."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Compute mean and std from training set only\n",
            "scaler_mean = train_df[sensor_cols].mean()\n",
            "scaler_std = train_df[sensor_cols].std()\n",
            "\n",
            "# Standardize\n",
            "train_scaled = (train_df[sensor_cols] - scaler_mean) / scaler_std\n",
            "test_scaled = (test_df[sensor_cols] - scaler_mean) / scaler_std\n",
            "\n",
            "print(\"Standardization completed successfully.\")\n",
            "train_scaled.describe().round(2).T[['mean', 'std', 'min', 'max']]"
        ]
    }
]

notebook_content = {
    "cells": cells,
    "metadata": {
        "language_info": {
            "name": "python",
            "version": "3.11"
        },
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

with open("gas_turbine_analysis.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook_content, f, indent=2)

print("gas_turbine_analysis.ipynb updated with Section 1 and Section 2.")
