import json
import os

notebook_content = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Data Analytics Project Work: Gas Turbine Emission & Energy Analysis\n",
                "**Course:** Data Analytics (and Data Driven Decision) — University of L'Aquila  \n",
                "**Dataset:** Gas Turbine CO and NOx Emission Data Set (2011–2015)  \n",
                "\n",
                "---\n",
                "## Project Guidelines Structure\n",
                "1. **Description of the dataset**\n",
                "2. **Data cleaning (if needed)**\n",
                "3. **Exploratory analysis**\n",
                "4. **Main analysis: objective and methods adopted**\n",
                "5. **Preview / summary of the results**\n",
                "6. **Detailed results**\n",
                "7. **Conclusions**\n",
                "\n",
                "---"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 0. Setup and Environment\n",
                "Importing standard libraries required for data manipulation, analysis, and visualization."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import numpy as np\n",
                "import pandas as pd\n",
                "import matplotlib.pyplot as plt\n",
                "import seaborn as sns\n",
                "\n",
                "# Set plot styling\n",
                "plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')\n",
                "plt.rcParams['figure.figsize'] = (10, 6)\n",
                "plt.rcParams['font.size'] = 11\n",
                "\n",
                "print(\"Environment initialized successfully.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 1. Description of the Dataset\n",
                "\n",
                "### 1.1 Context & Industrial Background\n",
                "The dataset contains **36,733 hourly aggregated records** of 11 sensor measurements collected from an operational gas turbine located in the north-western region of Turkey across five consecutive years (**2011 to 2015**).\n",
                "\n",
                "The primary goal is studying, modeling, and predicting flue gas emissions:\n",
                "- **Carbon Monoxide (CO)**: Indicator of incomplete combustion.\n",
                "- **Nitrogen Oxides (NOx = NO + NO2)**: Pollutants generated by high peak combustion temperatures (thermal NOx).\n",
                "- **Turbine Energy Yield (TEY)**: Net electrical energy production.\n",
                "\n",
                "### 1.2 Variable Definitions\n",
                "The 11 continuous features are categorized as follows:\n",
                "\n",
                "| Variable | Symbol | Unit | Category | Physical Role / Interpretation |\n",
                "| :--- | :--- | :--- | :--- | :--- |\n",
                "| Ambient Temperature | `AT` | °C | Ambient | Ambient intake air temperature; directly influences air density and mass flow. |\n",
                "| Ambient Pressure | `AP` | mbar | Ambient | Atmospheric barometric pressure surrounding the power plant. |\n",
                "| Ambient Humidity | `AH` | % | Ambient | Intake air relative humidity; affects combustion flame dynamics. |\n",
                "| Air Filter Diff. Pressure | `AFDP` | mbar | Turbine | Pressure drop across the intake air filter (indicator of fouling). |\n",
                "| Gas Turbine Exhaust Pressure | `GTEP` | mbar | Turbine | Exhaust gas backpressure in the exhaust duct. |\n",
                "| Turbine Inlet Temperature | `TIT` | °C | Turbine | Firing temperature of combustion gas entering turbine expander. |\n",
                "| Turbine After Temperature | `TAT` | °C | Turbine | Exhaust gas temperature measured downstream of the expander. |\n",
                "| Compressor Discharge Pressure | `CDP` | mbar | Turbine | Pressure of compressed air exiting compressor stage. |\n",
                "| Turbine Energy Yield | `TEY` | MWh | Output | Hourly net electrical energy output generated by the unit. |\n",
                "| Carbon Monoxide | `CO` | mg/m³ | Emission | Measured flue gas CO concentration (incomplete combustion). |\n",
                "| Nitrogen Oxides | `NOX` | mg/m³ | Emission | Measured flue gas NOx concentration (thermal oxidation). |\n",
                "\n",
                "### 1.3 Data Ingestion & Overview"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Define data path\n",
                "data_dir = os.path.join(\"data\", \"gas+turbine+co+and+nox+emission+data+set\")\n",
                "years = [2011, 2012, 2013, 2014, 2015]\n",
                "\n",
                "# Load individual year datasets\n",
                "dfs = []\n",
                "for y in years:\n",
                "    fpath = os.path.join(data_dir, f\"gt_{y}.csv\")\n",
                "    df_y = pd.read_csv(fpath)\n",
                "    df_y['year'] = y\n",
                "    dfs.append(df_y)\n",
                "    print(f\"Year {y}: {df_y.shape[0]:,d} observations, {df_y.shape[1]-1} sensor features\")\n",
                "\n",
                "# Combine all years into a master DataFrame\n",
                "df_all = pd.concat(dfs, ignore_index=True)\n",
                "print(f\"\\nTotal Combined Records: {df_all.shape[0]:,d} rows × {df_all.shape[1]} columns\")\n",
                "df_all.head()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### 1.4 Data Types and Summary Statistics\n",
                "Checking memory usage, column data types, null values, and summary statistics across the complete dataset."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Dataset concise info and null value check\n",
                "print(\"--- Data Information & Null Counts ---\")\n",
                "df_all.info()"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Descriptive statistics for all 11 sensor variables\n",
                "sensor_cols = ['AT', 'AP', 'AH', 'AFDP', 'GTEP', 'TIT', 'TAT', 'TEY', 'CDP', 'CO', 'NOX']\n",
                "summary_stats = df_all[sensor_cols].describe().T[['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']]\n",
                "summary_stats.columns = ['Count', 'Mean', 'Std Dev', 'Min', 'Q1 (25%)', 'Median (50%)', 'Q3 (75%)', 'Max']\n",
                "summary_stats.round(2)"
            ]
        }
    ],
    "metadata": {
        "language_info": {
            "name": "python",
            "version": "3.11"
        },
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

with open("gas_turbine_analysis.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook_content, f, indent=2)

print("gas_turbine_analysis.ipynb created successfully.")
